import streamlit as st
from pathlib import Path

st.set_page_config(
    page_title="Privacy Policy - AI Pipeline Studio",
    page_icon="🔒",
    layout="centered"
)

# -----------------------------
# Styles (Consistency Maintained)
# -----------------------------
st.markdown("""
    <style>
    .stApp {
        background: radial-gradient(circle at 50% 0%, #1e202e 0%, #000000 100%);
        color: #e0e0e0;
    }
    .privacy-header {
        font-size: 40px;
        font-weight: bold;
        color: #ffffff;
        border-bottom: 2px solid #00d2ff;
        padding-bottom: 10px;
        margin-bottom: 30px;
    }
    .section-card {
        background: rgba(255, 255, 255, 0.05);
        padding: 20px;
        border-radius: 10px;
        border-left: 4px solid #00d2ff;
        margin-bottom: 20px;
    }
    h3 { color: #85d7ff !important; }
    </style>
""", unsafe_allow_html=True)

# -----------------------------
# Content
# -----------------------------

# Back button
if st.button("← Back to Home"):
    st.switch_page("page1.py")

st.markdown('<div class="privacy-header">Privacy & Security Protocol</div>', unsafe_allow_html=True)

st.markdown("""
<div class="section-card">
    <h3>1. Data Processing Architecture</h3>
    <p>AI Pipeline Studio employs a <strong>Local-First</strong> strategy. Your uploaded CSV/Excel datasets are processed exclusively within the current runtime memory instance. Unless you explicitly configure cloud storage (e.g., S3/Blob), data never leaves your execution environment.</p>
</div>

<div class="section-card">
    <h3>2. AI Agent Interaction (Model Usage)</h3>
    <p>To generate code and analytical insights, the system transmits data summaries (Schema, column names, first 5 sample rows) to LLM providers (e.g., OpenAI/Azure).</p>
    <ul>
        <li>⚠️ <strong>Important:</strong> Please do not upload raw data containing PII (Personally Identifiable Information).</li>
        <li>✅ The system automatically anonymizes and hashes sample data when privacy mode is enabled.</li>
    </ul>
</div>

<div class="section-card">
    <h3>3. Artifact Storage</h3>
    <p>Generated reports, cleaned datasets, and model files are stored in the local <code>output/</code> directory. Please backup important artifacts promptly after closing the application, as temporary session files may be purged.</p>
</div>

<div class="section-card">
    <h3>4. Disclaimer</h3>
    <p>Code generated by this tool is provided for reference purposes only. Before deploying to production environments, mandatory human code review (Human-in-the-Loop) is required. The developers assume no liability for data loss resulting from direct use of AI-generated code without proper validation.</p>
</div>
""", unsafe_allow_html=True)

st.info("Last Updated: 2025-05-20 | Version: 2.0.1 Alpha")